Repository myplant-io/.github, pull requests merged in 2023-12, with the labels that each got.

#90 fix: add docker repository
  workflow-templates/docker-deploy.yml
  workflow-templates/gradle-deploy.yml
  workflow-templates/python-deploy.yml
  workflow-templates/yarn-deploy.yml
  workflow-templates/yarn2-deploy.yml
Labels: 1 min review

#88 fix: set docker context
  workflow-templates/python-deploy.yml
Labels: 1 min review

#86 feat: add python test
  workflow-templates/python-dependency-check.yml
  workflow-templates/python-deploy.yml
  workflow-templates/python-test.properties.json
  workflow-templates/python-test.yml
Labels: 5 min review

#96 chore: python test support poetry
  workflow-templates/python-test.yml
Labels: 1 min review, safe-changes
