Repository myplant-io/.github, pull requests merged in 2024-02, with the labels that each got.

#121 chore(fix): python-dependency-check to work with cyclonedx-py v4
  workflow-templates/python-dependency-check.yml
Labels: 1 min review

#122 feat: directly calling GitHub action in myplant-io/github-action repo
  workflow-templates/common-merge.yml
  workflow-templates/docker-deploy.yml
  workflow-templates/dotnet-dependency-check.yml
  workflow-templates/dotnet-deploy.yml
  workflow-templates/gradle-dependency-check.yml
  workflow-templates/gradle-deploy.yml
  workflow-templates/python-dependency-check.yml
  workflow-templates/python-deploy.yml
  workflow-templates/yarn-dependency-check.yml
  workflow-templates/yarn-deploy.yml
  workflow-templates/yarn2-dependency-check.yml
  workflow-templates/yarn2-deploy.yml
Labels: 5 min review

#124 feat: separate validate and test for python/yarn/yarn2
  workflow-templates/python-test.yml
  workflow-templates/yarn-test.yml
  workflow-templates/yarn2-test.yml
Labels: 5 min review, safe-changes

#125 fix: distinguish between pip and poetry cache
  workflow-templates/prefect-dependency-check.yml
  workflow-templates/python-dependency-check.yml
  workflow-templates/python-deploy.yml
  workflow-templates/python-test.yml
Labels: 5 min review

#128 feat: improve python test determination
  workflow-templates/python-test.yml
Labels: 1 min review, safe-changes

#130 fix: add python version determination
  workflow-templates/prefect-dependency-check.yml
  workflow-templates/prefect-deploy.yml
  workflow-templates/python-dependency-check.yml
  workflow-templates/python-deploy.yml
  workflow-templates/python-test.yml
Labels: 5 min review

#131 fix: syntax
  workflow-templates/prefect-dependency-check.yml
  workflow-templates/python-dependency-check.yml
  workflow-templates/python-deploy.yml
  workflow-templates/python-test.yml
Labels: 5 min review

#132 fix: install poetry early
  workflow-templates/python-test.yml
Labels: 1 min review, safe-changes

#133 fix: only install pre-commit if necessary (config file available)
  workflow-templates/python-test.yml
  workflow-templates/yarn2-dependency-check.yml
Labels: 1 min review

#134 fix: remove deprecated usage of set-output
  optional-workflows/create-release-branch.yml
  workflow-templates/prefect-dependency-check.yml
  workflow-templates/python-dependency-check.yml
  workflow-templates/python-deploy.yml
  workflow-templates/python-test.yml
Labels: 1 min review, missing-jira-ticket

#136 fix: add missing poetry installation
  workflow-templates/prefect-dependency-check.yml
  workflow-templates/python-dependency-check.yml
  workflow-templates/python-deploy.yml
Labels: 1 min review, missing-jira-ticket

#137 feat: prepare 1.1.0 release (add validation)
  .github/dependabot.yml
  .github/workflows/validate.yml
  .github/workflows/workflow-installer.yml
  README.md
  action.yml
  optional-workflows/combine-dependabot-pr.yml
  optional-workflows/create-release-branch.yml
  workflow-templates/common-auto-update.properties.json
  workflow-templates/common-auto-update.yml
  workflow-templates/common-merge.yml
  workflow-templates/common-sonarqube.yml
  workflow-templates/docker-deploy.yml
  workflow-templates/dotnet-dependency-check.yml
  workflow-templates/dotnet-deploy.yml
  workflow-templates/dotnet-sonarqube.yml
  workflow-templates/dotnet-test.yml
  workflow-templates/go-dependency-check.yml
  workflow-templates/go-deploy.yml
  workflow-templates/go-sonarqube.yml
  workflow-templates/gradle-dependency-check.yml
  workflow-templates/gradle-deploy.yml
  workflow-templates/gradle-sonarqube.yml
  workflow-templates/gradle-test.yml
  workflow-templates/prefect-dependency-check.yml
  workflow-templates/prefect-deploy.yml
  workflow-templates/prefect-sonarqube.yml
  workflow-templates/python-dependency-check.yml
  workflow-templates/python-deploy.yml
  workflow-templates/python-sonarqube.yml
  workflow-templates/python-test.yml
  workflow-templates/yarn-dependency-check.yml
  workflow-templates/yarn-deploy.yml
  workflow-templates/yarn-sonarqube.yml
  workflow-templates/yarn-test.yml
  workflow-templates/yarn2-dependency-check.yml
  workflow-templates/yarn2-deploy.yml
  workflow-templates/yarn2-sonarqube.yml
  workflow-templates/yarn2-test.yml
Labels: 10 min review

#139 chore: increase version number
  workflow-templates/common-auto-update.yml
Labels: 1 min review

#141 fix: pytest for pip condition
  workflow-templates/common-auto-update.yml
  workflow-templates/python-test.yml
Labels: 1 min review

#145 fix: after release merge
  .github/workflows/merge.yml
Labels: 1 min review

#150 fix: label creation for merge
  .github/workflows/merge.yml
  workflow-templates/common-merge.yml
Labels: 1 min review, missing-jira-ticket

#151 fix: add merge gh token
  .github/workflows/merge.yml
  workflow-templates/common-merge.yml
Labels: 1 min review, missing-jira-ticket

#152 fix: add merge gh token
  .github/workflows/merge.yml
  workflow-templates/common-merge.yml
Labels: 1 min review, missing-jira-ticket

#158 fix: run validation (not test) in validation job
  workflow-templates/yarn-test.yml
Labels: 1 min review, safe-changes

#155 chore(release): merge v1.1.2 back into master
  workflow-templates/common-auto-update.yml
  workflow-templates/prefect-dependency-check.yml
  workflow-templates/python-test.yml
  workflow-templates/yarn-test.yml
  workflow-templates/yarn2-test.yml
Labels: 5 min review

#157 fix: use general javaVersion task
  workflow-templates/gradle-dependency-check.yml
  workflow-templates/gradle-deploy.yml
  workflow-templates/gradle-sonarqube.yml
  workflow-templates/gradle-test.yml
Labels: 1 min review

#160 fix: remove misleading log output for gradle (var was never set)
  workflow-templates/gradle-sonarqube.yml
Labels: 1 min review

#162 chore(release): v1.1.3
  workflow-templates/common-auto-update.yml
  workflow-templates/go-dependency-check.yml
  workflow-templates/go-sonarqube.yml
  workflow-templates/gradle-dependency-check.yml
  workflow-templates/gradle-deploy.yml
  workflow-templates/gradle-sonarqube.yml
  workflow-templates/gradle-test.yml
  workflow-templates/yarn-test.yml
Labels: 1 min review

#164 fix: add missing version information
  workflow-templates/go-dependency-check.yml
  workflow-templates/go-deploy.yml
  workflow-templates/prefect-dependency-check.yml
Labels: 1 min review

#165 fix: add name for step
  workflow-templates/common-sonarqube.yml
  workflow-templates/docker-deploy.yml
  workflow-templates/dotnet-dependency-check.yml
  workflow-templates/dotnet-deploy.yml
  workflow-templates/dotnet-sonarqube.yml
  workflow-templates/dotnet-test.yml
  workflow-templates/go-dependency-check.yml
  workflow-templates/go-deploy.yml
  workflow-templates/go-sonarqube.yml
  workflow-templates/gradle-dependency-check.yml
  workflow-templates/gradle-deploy.yml
  workflow-templates/gradle-sonarqube.yml
  workflow-templates/gradle-test.yml
  workflow-templates/prefect-dependency-check.yml
  workflow-templates/prefect-deploy.yml
  workflow-templates/prefect-sonarqube.yml
  workflow-templates/python-dependency-check.yml
  workflow-templates/python-deploy.yml
  workflow-templates/python-sonarqube.yml
  workflow-templates/python-test.yml
  workflow-templates/yarn-dependency-check.yml
  workflow-templates/yarn-deploy.yml
  workflow-templates/yarn-sonarqube.yml
  workflow-templates/yarn-test.yml
  workflow-templates/yarn2-dependency-check.yml
  workflow-templates/yarn2-deploy.yml
  workflow-templates/yarn2-sonarqube.yml
  workflow-templates/yarn2-test.yml
Labels: 5 min review
