Repository myplant-io/.github, pull requests merged in 2024-08, with the labels that each got.

#214 feat: sonar jdk updates
  .github/workflows/merge.yml
  .github/workflows/validate.yml
  .github/workflows/workflow-installer.yml
  workflow-templates/dotnetCore-dependency-check.yml
  workflow-templates/dotnetFramework-deploy.yml
  workflow-templates/dotnetFramework-sonarqube.yml
  workflow-templates/gradle-dependency-check.yml
  workflow-templates/gradle-sonarqube.yml
Labels: 10 min review

#217 fix: junit test reports folder determination
  workflow-templates/gradle-sonarqube.yml
Labels: 1 min review

#215 fix: removing deprecated gradle-setup usage (and following migration guide)
  workflow-templates/gradle-dependency-check.yml
  workflow-templates/gradle-deploy.yml
  workflow-templates/gradle-sonarqube.yml
  workflow-templates/gradle-test.yml
Labels: 5 min review

#218 fix: syntax of sonarqube gh action
  workflow-templates/gradle-sonarqube.yml
Labels: 1 min review

#220 feat: improvements in calling sonar-scanner when there are no tests
  workflow-templates/python-sonarqube.yml
Labels: 1 min review

#221 fix: sonar key and name determination
  README.md
  workflow-templates/gradle-sonarqube.yml
Labels: 1 min review, missing-tests

#223 chore(deps): upgrade to setup-gradle@v4
  workflow-templates/gradle-dependency-check.yml
  workflow-templates/gradle-deploy.yml
  workflow-templates/gradle-sonarqube.yml
  workflow-templates/gradle-test.yml
Labels: 5 min review

#225 chore(release): merging v1.3.1 back to master
  .github/workflows/deploy.yml
  .github/workflows/merge.yml
  .github/workflows/validate.yml
  .github/workflows/workflow-installer.yml
  README.md
  workflow-templates/common-auto-update.yml
  workflow-templates/common-merge.yml
  workflow-templates/docker-deploy.yml
  workflow-templates/dotnetCore-dependency-check.yml
  workflow-templates/dotnetCore-deploy.yml
  workflow-templates/dotnetFramework-deploy.yml
  workflow-templates/dotnetFramework-sonarqube.yml
  workflow-templates/go-deploy.yml
  workflow-templates/go-sonarqube.yml
  workflow-templates/gradle-dependency-check.yml
  workflow-templates/gradle-deploy.yml
  workflow-templates/gradle-sonarqube.yml
  workflow-templates/gradle-test.yml
  workflow-templates/prefect-deploy.yml
  workflow-templates/python-deploy.yml
  workflow-templates/python-sonarqube.yml
  workflow-templates/yarn-deploy.yml
  workflow-templates/yarn2-deploy.yml
Labels: 20 min review

#227 fix: DD-49398 exclude _test.go files from coverage calculation (also for PR runs)
  workflow-templates/go-sonarqube.yml
Labels: 1 min review

#228 fix: workflow syntax
  workflow-templates/gradle-dependency-check.yml
Labels: 1 min review

#233 chore: update prefect actions to match latest python ones
  workflow-templates/prefect-dependency-check.yml
  workflow-templates/prefect-sonarqube.yml
Labels: 5 min review
