Repository myplant-io/.github, pull requests merged in 2024-07, with the labels that each got.

#204 chore(release): merge release/1.2.0 into master
  workflow-templates/common-auto-update.yml
  workflow-templates/docker-deploy.yml
  workflow-templates/go-deploy.yml
  workflow-templates/prefect-deploy.yml
  workflow-templates/python-deploy.yml
  workflow-templates/yarn-deploy.yml
  workflow-templates/yarn2-deploy.yml
Labels: 5 min review

#206 chore(release): merging release back to master
  workflow-templates/common-auto-update.yml
  workflow-templates/docker-deploy.yml
  workflow-templates/dotnetCore-deploy.yml
  workflow-templates/dotnetCore-test.yml
  workflow-templates/go-deploy.yml
  workflow-templates/gradle-deploy.yml
  workflow-templates/gradle-test.yml
  workflow-templates/prefect-deploy.yml
  workflow-templates/python-deploy.yml
  workflow-templates/yarn-deploy.yml
  workflow-templates/yarn-test.yml
  workflow-templates/yarn2-deploy.yml
  workflow-templates/yarn2-test.yml
Labels: 5 min review

#207 chore: add sonar prefix documentation for python
  README.md
Labels: 1 min review, safe-changes

#209 fix: DD-49216 execute all tests recursively to calculate test coverage for Go projects
  workflow-templates/go-sonarqube.yml
Labels: 1 min review

#210 fix/DD 49216 GoTestCoverage2
  workflow-templates/go-sonarqube.yml
Labels: 1 min review

#211 fix: sonar java setup
  workflow-templates/common-auto-update.yml
  workflow-templates/gradle-sonarqube.yml
Labels: 1 min review

#212 feat: using coverage to get correct stats in sonar
  workflow-templates/python-sonarqube.yml
Labels: 1 min review

#213 feat: upgrade to mikepenz/release-changelog-builder-action@v5
  workflow-templates/docker-deploy.yml
  workflow-templates/dotnetCore-deploy.yml
  workflow-templates/go-deploy.yml
  workflow-templates/gradle-deploy.yml
  workflow-templates/prefect-deploy.yml
  workflow-templates/python-deploy.yml
  workflow-templates/yarn-deploy.yml
  workflow-templates/yarn2-deploy.yml
Labels: 5 min review
