Repository myplant-io/.github, pull requests merged in 2024-01, with the labels that each got.

#100 chore: using sonar.token instead of sonar.login
  workflow-templates/common-sonarqube.yml
  workflow-templates/go-sonarqube.yml
  workflow-templates/gradle-sonarqube.yml
  workflow-templates/prefect-sonarqube.yml
  workflow-templates/python-sonarqube.yml
  workflow-templates/yarn-sonarqube.yml
  workflow-templates/yarn2-sonarqube.yml
Labels: 1 min review

#101 feat: add auto determination for DOCKER_REPOSITORY
  workflow-templates/docker-deploy.yml
  workflow-templates/go-deploy.yml
  workflow-templates/gradle-deploy.yml
  workflow-templates/prefect-deploy.yml
  workflow-templates/python-deploy.yml
  workflow-templates/yarn-deploy.yml
  workflow-templates/yarn2-deploy.yml
Labels: 5 min review

#102 chore: prefect releases to prod
  README.md
  workflow-templates/prefect-deploy.yml
Labels: 1 min review, missing-tests

#103 feat: add docker caching to github
  workflow-templates/docker-deploy.yml
  workflow-templates/go-deploy.yml
  workflow-templates/prefect-deploy.yml
  workflow-templates/python-deploy.yml
  workflow-templates/yarn-deploy.yml
  workflow-templates/yarn2-deploy.yml
Labels: 1 min review

#107 feat: pass nvd.apiKey to gradle
  workflow-templates/gradle-dependency-check.yml
Labels: 1 min review

#105 fix: use nvmrc instead of matrix for node version determination
  README.md
  workflow-templates/common-auto-update.yml
  workflow-templates/common-merge.yml
  workflow-templates/common-sonarqube.yml
  workflow-templates/docker-deploy.yml
  workflow-templates/dotnet-dependency-check.yml
  workflow-templates/dotnet-deploy.yml
  workflow-templates/dotnet-sonarqube.yml
  workflow-templates/dotnet-test.yml
  workflow-templates/go-dependency-check.yml
  workflow-templates/go-deploy.yml
  workflow-templates/go-sonarqube.yml
  workflow-templates/gradle-dependency-check.yml
  workflow-templates/gradle-deploy.yml
  workflow-templates/gradle-sonarqube.yml
  workflow-templates/gradle-test.yml
  workflow-templates/prefect-dependency-check.yml
  workflow-templates/prefect-deploy.yml
  workflow-templates/prefect-sonarqube.yml
  workflow-templates/python-dependency-check.yml
  workflow-templates/python-deploy.yml
  workflow-templates/python-sonarqube.yml
  workflow-templates/python-test.yml
  workflow-templates/yarn-dependency-check.yml
  workflow-templates/yarn-deploy.yml
  workflow-templates/yarn-sonarqube.yml
  workflow-templates/yarn-test.yml
  workflow-templates/yarn2-dependency-check.yml
  workflow-templates/yarn2-deploy.yml
  workflow-templates/yarn2-sonarqube.yml
  workflow-templates/yarn2-test.yml
Labels: 10 min review

#112 fix: change poetry detection to poetry.lock
  workflow-templates/python-test.yml
Labels: 1 min review, safe-changes

#113 fix: replace archived action
  workflow-templates/common-merge.yml
Labels: 1 min review
